### ISSUE TITLE
conda install on windows?

### ISSUE THREAD

**Issue by rjleveque** [clawpack/conda-recipes#2]
A student asked if it's possible to use the conda installer on windows.  It didn't seem to work, with the message `clawpack missing in current win-64 channels`, see screen shot.  

<img width="674" alt="conda_windows" src="https://cloud.githubusercontent.com/assets/720122/22180123/2fb20cfa-e01c-11e6-82cf-e3d1f571f1a4.png">

**Comment by ketch** [comment]
Yes. I thought I only mentioned packages for linux and mac. Nobody has built it with conda on a windows machine.
